### ISSUE TITLE
Alert says OK even in case of failed API request

### ISSUE THREAD

**Issue by lubo-makky** [MaverickEngine/summary-engine#3]
When API request `POST /wp-json/summaryengine/v1/summarise` fails, javascript alert says OK

![Screenshot 2023-02-03 at 17 22 59](https://user-images.githubusercontent.com/7994456/216658470-ec3df59e-315d-4336-850e-02a645fdb7f0.png)

There is an hidden error in console:
 
![Screenshot 2023-02-03 at 17 42 13](https://user-images.githubusercontent.com/7994456/216658538-bcc8b4fa-ff45-454e-a7c9-d2fd2b863933.png)

**Comment by j-norwood-young** [comment]
Fixed in v0.11.1
