### ISSUE TITLE
OpenAI API response with error message is not recognized as failed

### ISSUE THREAD

**Issue by lubo-makky** [MaverickEngine/summary-engine#4]
If OpenAI API response in `SummaryEngineOpenAI::summarise` contais an error, it is not recognized as failed request. Only transport errors are handled via `is_wp_error` function. 

Example error message from OpenAI API:

```json
{
    "error":{
        "message":"This model's maximum context length is 2049 tokens, however you requested 3068 tokens (2768 in your prompt; 300 for the completion). Please reduce your prompt; or completion length.",
        "type":"invalid_request_error",
        "param":null,
        "code":null
    }
}
```

This message should be presented to user, because he or she needs to change settings.

**Comment by j-norwood-young** [comment]
Fixed in v0.11.1
